pekko {
  actor {
    serialize-messages = off
    serializers {
      user-account-event = "io.github.j5ik2o.pcqrses.command.interfaceAdapter.aggregate.users.UserAccountEventSerializer"
      product-event = "io.github.j5ik2o.pcqrses.command.interfaceAdapter.aggregate.inventory.ProductEventSerializer"
      inventory-event = "io.github.j5ik2o.pcqrses.command.interfaceAdapter.aggregate.inventory.InventoryEventSerializer"
      customer-event = "io.github.j5ik2o.pcqrses.command.interfaceAdapter.aggregate.inventory.CustomerEventSerializer"
      warehouse-event = "io.github.j5ik2o.pcqrses.command.interfaceAdapter.aggregate.inventory.WarehouseEventSerializer"
      warehouse-zone-event = "io.github.j5ik2o.pcqrses.command.interfaceAdapter.aggregate.inventory.WarehouseZoneEventSerializer"
    }
    serialization-bindings {
      "io.github.j5ik2o.pcqrses.command.domain.users.UserAccountEvent" = user-account-event
      "io.github.j5ik2o.pcqrses.command.domain.inventory.ProductEvent" = product-event
      "io.github.j5ik2o.pcqrses.command.domain.inventory.InventoryEvent" = inventory-event
      "io.github.j5ik2o.pcqrses.command.domain.inventory.CustomerEvent" = customer-event
      "io.github.j5ik2o.pcqrses.command.domain.inventory.WarehouseEvent" = warehouse-event
      "io.github.j5ik2o.pcqrses.command.domain.inventory.WarehouseZoneEvent" = warehouse-zone-event
    }
    serialization-identifiers {
      "io.github.j5ik2o.pcqrses.command.interfaceAdapter.aggregate.users.UserAccountEventSerializer" = 20002
      "io.github.j5ik2o.pcqrses.command.interfaceAdapter.aggregate.inventory.ProductEventSerializer" = 30001
      "io.github.j5ik2o.pcqrses.command.interfaceAdapter.aggregate.inventory.InventoryEventSerializer" = 30002
      "io.github.j5ik2o.pcqrses.command.interfaceAdapter.aggregate.inventory.CustomerEventSerializer" = 30003
      "io.github.j5ik2o.pcqrses.command.interfaceAdapter.aggregate.inventory.WarehouseEventSerializer" = 30004
      "io.github.j5ik2o.pcqrses.command.interfaceAdapter.aggregate.inventory.WarehouseZoneEventSerializer" = 30005
    }
  }
}
